### ISSUE TITLE
SEO: Mobile UI Optimization

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1684]
Mobile UI improvements:

- [x] Tap targets are too small and close: I couldn't identify what exactly is the issue on these pages. Would be great if one can double-check before we discard this issue. [affected pages](https://docs.google.com/spreadsheets/d/1OE1clMOXijFRYCIx_k87cGiysBE4RWdcwklBYJvEklo/edit#gid=0)
- [ ] Content does not size correctly to viewport. [affected pages](https://docs.google.com/spreadsheets/d/1KBDTqzqk_J3ZF-SQlqv_ji-wMpAyDxRWhPDilKYlZRQ/edit#gid=0)
example:
<img width="395" alt="Bildschirmfoto 2022-03-01 um 11 09 34" src="https://user-images.githubusercontent.com/46345125/156149593-d70f32cb-ea1c-4afb-91c1-17fb7707e1db.png">

**Comment by nisarhassan12** [comment]
@chrifro with fixing the issue specified in the [above comment](https://github.com/gitpod-io/website/issues/1684#issuecomment-1071076357) I tested all of the pages apart from all the individual docs,blog, changelog and screencasts pages. 

> - [ ]  Tap targets are too small and close

I spotted it here [1](https://github.com/gitpod-io/website/issues/1782), [2](https://github.com/gitpod-io/website/issues/1776) and another place specified below where this happens and that is the Privacy page. Do you think should I update it to have more spacing between the list items?

Also, would it make sense to go through if not all then at test least 10, 10 pages on docs, blog and all the changelog and screencasts pages and test for this issue? What about changing the spacing between the list items globally? 

![Screen Shot 2022-03-18 at 1 30 24 AM](https://user-images.githubusercontent.com/46004116/158890021-2f9d0561-0338-4624-b25e-be14ce88f1df.png)

**Comment by nisarhassan12** [comment]
> - [ ] Content does not size correctly to viewport.

@chrifro I'm not able to find out this issue I tested with Lighthouse and the issue was not reported there. I think it is already fixed and looking at the pages nothing seems to be suspicious.

**Comment by chrifro** [comment]
>What about changing the spacing between the list items globally by a bit?

Isn't the spacing for lists globally defined? It would then be best to adjust the spacing by a couple of pixels. 

>I'm not able to find out this issue I tested with Lighthouse and the issue was not reported there. I think it is already fixed and looking at the pages nothing seems to be suspicious.

I just checked https://www.gitpod.io/docs/quickstart/clojure and the issue persistes when resizing the window size
<img width="507" alt="Bildschirmfoto 2022-04-05 um 09 54 22" src="https://user-images.githubusercontent.com/46345125/161706123-40892938-176b-4312-92a8-3fad01de7300.png">
Same for https://www.gitpod.io/docs/quickstart/react

**Comment by nisarhassan12** [comment]
> I just checked https://www.gitpod.io/docs/quickstart/clojure and the issue persistes when resizing the window size

@Cahllagerfeld I'm unable to reproduce this. Can you have a look when you get the time? Thanks
