### ISSUE TITLE
page loading: font size changes while loading the page

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#776]
When opening www.gitpod.io the font size changes during the loading. See 0:03-0:04 in the screencast

https://user-images.githubusercontent.com/46345125/126606925-76aced0f-2f22-4479-b817-671c389e4849.mov

**Comment by nisarhassan12** [comment]
Thanks @ChristinFrohne for bringing this up. 

The way it currently behaves is expected i.e meanwhile the fonts are loading display the site using the fallback fonts and once the actual fonts are available swap to them. We could change this behavoir to block the rendering of the site unless the fonts are loaded but that is gonna slow down the rendering and make the site look slower.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have attempted a fix here in this Pr https://github.com/gitpod-io/website/pull/801 Please let me know if that helps.

**Comment by ChristinFrohne** [comment]
Thanks for the explanation @nisarhassan12  

The twitch is really visible because the position of the text changes as well. Could that be fixed? 

For example, I compared it to vercel.com. There is a minor twitch as well, but the position stays the same, so it's almost not visible. 
I couldn't see any improvements when testing your PR

**Comment by ChristinFrohne** [comment]
@nisarhassan12 
What did you do to fix this issue? 

I just tested it and the issue is still there



https://user-images.githubusercontent.com/46345125/127872016-2c9ef4a7-ff68-4da7-b6f3-3eaf2375ff0f.mov

**Comment by nisarhassan12** [comment]
Thanks. I tested it in Chrome, Safari and Firefox and the issue for me no longer seems to be there for me. 

https://user-images.githubusercontent.com/46004116/127872605-6e60b1de-7b23-438c-b4d3-3e5da9a38132.mov

Can you share which browser are you on ? and what is the viewport width in px where this problem happens you can find this out by opening the dev tools then heading over to the console and typing `window.innerWidth` make sure the dev tools are docked at the bottom. 

To fix the issue I widened the container which contains the headline.

**Comment by ChristinFrohne** [comment]
There is no twitch if I reload the page. The loading issue is only there when I come from another page e.g. Google. I noticed that the twitch is not always there depending on the viewpoint width

Browser: Chrome
Viewport width: 1264

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne for reporting this. I'm also able to reproduce this. 

@mikenikles I spent quite a lot of time trying to fix this but I'm unable to do so. Can you look into it when you get some time? Thanks

**Comment by mikenikles** [comment]
I pushed a fix in #806 for this. We now tell the browser to preload the two fonts we use so that the font is ready by the time rendering of the page starts.

**Comment by nisarhassan12** [comment]
Thanks, @mikenikles It indeed works a lot better. 

If I use network throttling use Fast 3G I still see the flicker but that is expected, right ? 

https://user-images.githubusercontent.com/46004116/128140737-332889c5-4205-46cc-83a1-2c11e0ad5603.mov

**Comment by ChristinFrohne** [comment]
Thanks, Mike. ❤️ Works perfectly now with my Internet connection.
